### Check Username
GET http://localhost:8080/api/users/check-username?username=testuser
Content-Type: application/json

### Check Email
GET http://localhost:8080/api/users/check-email?email=sehan@mail.com
Content-Type: application/json

### 회원 가입
POST http://localhost:8080/userreg
Content-Type: application/x-www-form-urlencoded

username=postTeste4r&password=Vkdlf123!&name=John_Doe4&email=john2@example.com


### Check Email
POST http://localhost:8080/login
Content-Type: application/x-www-form-urlencoded

username=testuser&password=Vkdlf123!

### tset
GET http://localhost:8080/testuser
Content-Type: application/json

###
# Request to get trending posts for the week
GET http://localhost:8080/api/v1/trending/week
Content-Type: application/json

###
# Request to get trending posts for the month
GET http://localhost:8080/api/v1/trending/month
Content-Type: application/json

###
# Request to get trending posts for the week with pagination
GET http://localhost:8080/api/v1/trending/week?page=1&size=2
Content-Type: application/json

###
# Request to get trending posts for the month with pagination
GET http://localhost:8080/api/v1/trending/month?page=1&size=2
Content-Type: application/json

###
# 최근 글 확인
GET http://localhost:8080/api/v1/recent
Content-Type: application/json

###
# 글 디테일 테스트
GET http://localhost:8080/vlog.io/@sehan/recent test
Content-Type: application/json